import {
    faBook,
    faBookOpen,
    faChartLine,
    faCheck,
    faCheckSquare,
    faCog,
    faExclamationTriangle,
    faEye,
    faFilm,
    faHeart,
    faQuestionCircle,
    faSearch,
    faSearchPlus,
    faSignOutAlt,
    faTimes,
    faUser,
    faUserPlus,
    faTrash,
    faMinusCircle,
} from '@fortawesome/free-solid-svg-icons';

import { faGithub } from '@fortawesome/free-brands-svg-icons';
import { library } from '@fortawesome/fontawesome-svg-core';

library.add(
    faBook,
    faBookOpen,
    faChartLine,
    faCheck,
    faCheckSquare,
    faCog,
    faExclamationTriangle,
    faEye,
    faFilm,
    faHeart,
    faQuestionCircle,
    faSearch,
    faSearchPlus,
    faSignOutAlt,
    faTimes,
    faUser,
    faUserPlus,
    faGithub,
    faTrash,
    faMinusCircle,
);
